apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: chamankarsahil/backend-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: java
          protocol: TCP
          containerPort: 8080
