apiVersion: v1
kind: Pod
metadata:
  name: myvolhostpath
spec:
  containers:
  - image: ubuntu
    name: testc
    command: ["/bin/bash", "-c", "sleep 15000"]
    volumeMounts:
    - mountPath: /temp/hostpath
      name: testvolume
  volumes:
  - name: testvolume
    hostPath:
      path: /temp/data 